import Header from "./components/Header";
import "./globals.css";

export const metadata = {
  title: "Phasmophobia Journal",
  description: "Generated by create next app",
  icons: {
    icon: "/image.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header/ >
        {children}
      </body>
    </html>
  );
}
